# Generated by Django 3.0.4 on 2020-03-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(blank=True, db_column='balance', default=0, help_text='Coins earned by playing', verbose_name='Game Balance')),
                ('donate', models.PositiveIntegerField(blank=True, db_column='column', default=0, help_text='Coins obtained by donations', verbose_name='Donate Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Balance',
                'verbose_name_plural': 'User Balance',
                'db_table': 'user_balance',
            },
        ),
    ]
