# Generated by Django 3.0.4 on 2020-03-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20200321_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Points earned/losed by good/bad behaviour', verbose_name='Karma'),
        ),
    ]
